# Generated by Django 5.0.1 on 2024-01-05 16:17

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Write_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(max_length=50)),
                ('name_leader', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('number_players', models.IntegerField()),
                ('comment', models.TextField()),
                ('certificate', models.TextField()),
                ('promo_code', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
