# Generated by Django 5.0.1 on 2024-01-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_placequiz_quizgame_writequiz_delete_write_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgame',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Запись открыта'),
        ),
    ]
